language: ruby
rvm:
  - 2.0.0

before_script:
  - bundle install
  - bundle exec rake db:migrate
  - bundle exec rails s -d

script:
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
  - cucumber
